GenPO-v0:
  env_wrapper: nasim.generalized_envs.augmented_obs_wrapper.AugmentedObsWrapper
  n_envs: 8
  n_timesteps: !!float 1e7
  policy: 'MlpPolicy'
  batch_size: 128
  clip_range: 0.2
  ent_coef: 0.01
  gae_lambda: 0.9
  gamma: 0.999
  learning_rate: 0.0003
  max_grad_norm: 1
  n_epochs: 10
  n_steps: 1024
  vf_coef: 0.3
  policy_kwargs: "dict(
                  ortho_init=False,
                  activation_fn=nn.ReLU,
                  net_arch=dict(pi=[256, 256], vf=[256, 256]),
                )"